/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    functions: Function;
    completions: Completion;
    datasets: Dataset;
    data: Datum;
    evals: Eval;
    evalRuns: EvalRun;
    evalResults: EvalResult;
    functionCalls: FunctionCall;
    modelGroups: ModelGroup;
    models: Model;
    prompts: Prompt;
    providers: Provider;
    schemas: Schema;
    tenants: Tenant;
    users: User;
    workflows: Workflow;
    workflowCalls: WorkflowCall;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    functions: {
      functionCalls: 'functionCalls';
    };
    datasets: {
      data: 'data';
      evals: 'evals';
    };
    evalRuns: {
      results: 'evalResults';
    };
    modelGroups: {
      models: 'models';
    };
    providers: {
      models: 'models';
    };
    workflows: {
      workflowRuns: 'workflowCalls';
    };
  };
  collectionsSelect: {
    functions: FunctionsSelect<false> | FunctionsSelect<true>;
    completions: CompletionsSelect<false> | CompletionsSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    data: DataSelect<false> | DataSelect<true>;
    evals: EvalsSelect<false> | EvalsSelect<true>;
    evalRuns: EvalRunsSelect<false> | EvalRunsSelect<true>;
    evalResults: EvalResultsSelect<false> | EvalResultsSelect<true>;
    functionCalls: FunctionCallsSelect<false> | FunctionCallsSelect<true>;
    modelGroups: ModelGroupsSelect<false> | ModelGroupsSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    prompts: PromptsSelect<false> | PromptsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    schemas: SchemasSelect<false> | SchemasSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    workflows: WorkflowsSelect<false> | WorkflowsSelect<true>;
    workflowCalls: WorkflowCallsSelect<false> | WorkflowCallsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      updateModels: TaskUpdateModels;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "functions".
 */
export interface Function {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  deployment?: ('dev' | 'test' | 'prod') | null;
  active?: boolean | null;
  modelGroup?: (string | null) | ModelGroup;
  output: 'Object' | 'Text';
  schema?: (string | null) | Schema;
  code?: {
    system?: string | null;
    user?: string | null;
    types?: string | null;
    validation?: string | null;
    deployment?: string | null;
  };
  workflows?: (string | Workflow)[] | null;
  functionCalls?: {
    docs?: (string | FunctionCall)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  evals?: (string | Eval)[] | null;
  prompts?: (string | Prompt)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  domain?: string | null;
  apiKey?: string | null;
  active?: boolean | null;
  deployed?: boolean | null;
  functions?: (string | Function)[] | null;
  users?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  active?: boolean | null;
  avatar?: string | null;
  role: 'admin' | 'editor' | 'viewer';
  permissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  preferences?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tenants?:
    | {
        tenant: string | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelGroups".
 */
export interface ModelGroup {
  id: string;
  name: string;
  family?: string | null;
  version?: string | null;
  active?: boolean | null;
  /**
   * Models in this group
   */
  models?: {
    docs?: (string | Model)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  functions?: (string | Function)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  modelGroup?: (string | null) | ModelGroup;
  provider?: (string | null) | Provider;
  created?: string | null;
  contextLength?: number | null;
  architecture?: {
    modality?: string | null;
    tokenizer?: string | null;
    instructType?: string | null;
  };
  pricing?: {
    prompt?: string | null;
    completion?: string | null;
    image?: string | null;
    request?: string | null;
  };
  capabilities?: {
    contextLength?: number | null;
    maxCompletionTokens?: number | null;
    isModerated?: boolean | null;
    multimodal?: boolean | null;
    tools?: boolean | null;
    vision?: boolean | null;
  };
  perRequestLimits?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  models?: {
    docs?: (string | Model)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  endpoint?: string | null;
  apiUrl?: string | null;
  apiKey?: string | null;
  organizationId?: string | null;
  authType?: ('apiKey' | 'oauth' | 'bearer' | 'none') | null;
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  headers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tools?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schemas".
 */
export interface Schema {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  schema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schemaYaml?: string | null;
  type?: ('json' | 'typescript' | 'openai') | null;
  version?: string | null;
  functions?: (string | Function)[] | null;
  models?: (string | Model)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  deployed?: boolean | null;
  active?: boolean | null;
  functions?: (string | Function)[] | null;
  /**
   * Runs of this workflow
   */
  workflowRuns?: {
    docs?: (string | WorkflowCall)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  steps?:
    | {
        name: string;
        order?: number | null;
        type: 'function' | 'condition' | 'loop' | 'input' | 'output';
        function?: (string | null) | Function;
        condition?: string | null;
        loopConfig?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        inputConfig?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        outputConfig?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflowCalls".
 */
export interface WorkflowCall {
  id: string;
  workflow: string | Workflow;
  input:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timestamp: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  error?: string | null;
  duration?: number | null;
  success?: boolean | null;
  logs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  functionCalls?: (string | FunctionCall)[] | null;
  steps?:
    | {
        stepId: string;
        stepName: string;
        stepOrder?: number | null;
        status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped';
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        error?: string | null;
        startTime?: string | null;
        endTime?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "functionCalls".
 */
export interface FunctionCall {
  id: string;
  function: string | Function;
  model?: (string | null) | Model;
  input:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timestamp: string;
  status: 'pending' | 'running' | 'completed' | 'failed';
  error?: string | null;
  duration?: number | null;
  cost?: number | null;
  tokens?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Additional metadata for the function call
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  data?: (string | Datum)[] | null;
  workflow?: (string | null) | Workflow;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data".
 */
export interface Datum {
  id: string;
  dataset?: (string | null) | Dataset;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  format?: ('text' | 'json' | 'blob') | null;
  createdAt: string;
  updatedAt: string;
  extractedFrom?: string | null;
  embeddingType?: string | null;
  embeddingDim?: number | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  blob?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  functionCalls?: (string | FunctionCall)[] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  source?: string | null;
  imported?: string | null;
  version?: string | null;
  collection?: boolean | null;
  format?: ('text' | 'json' | 'csv' | 'images' | 'mixed') | null;
  data?: {
    docs?: (string | Datum)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  evals?: {
    docs?: (string | Eval)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evals".
 */
export interface Eval {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type?: ('accuracy' | 'performance' | 'robustness' | 'safety' | 'custom') | null;
  method?: string | null;
  metric?: string | null;
  dataset?: (string | null) | Dataset;
  functions?: (string | Function)[] | null;
  evalRuns?: (string | EvalRun)[] | null;
  resultsTable?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evalRuns".
 */
export interface EvalRun {
  id: string;
  eval: string | Eval;
  model?: (string | null) | Model;
  function?: (string | null) | Function;
  dataset?: (string | null) | Dataset;
  results?: {
    docs?: (string | EvalResult)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  startTime: string;
  endTime?: string | null;
  metrics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  summary?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'pending' | 'running' | 'completed' | 'failed';
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evalResults".
 */
export interface EvalResult {
  id: string;
  evalRun: string | EvalRun;
  metrics:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  score?: number | null;
  pass?: boolean | null;
  createdAt: string;
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  summary?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts".
 */
export interface Prompt {
  id: string;
  name: string;
  content: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  version?: string | null;
  template?: boolean | null;
  category?: string | null;
  functions?: (string | Function)[] | null;
  variables?:
    | {
        name: string;
        description?: string | null;
        defaultValue?: string | null;
        required?: boolean | null;
        type?: ('string' | 'number' | 'boolean' | 'object' | 'array') | null;
        id?: string | null;
      }[]
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "completions".
 */
export interface Completion {
  id: string;
  tenant?: (string | null) | Tenant;
  function?: (string | null) | Function;
  functionName?: string | null;
  model?: (string | null) | Model;
  hash?: string | null;
  requestId?: string | null;
  seed?: number | null;
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reasoning?: string | null;
  duration?: number | null;
  provider?: string | null;
  refusal?: string | null;
  error?: string | null;
  validation?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  debug?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'updateModels';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'updateModels') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'functions';
        value: string | Function;
      } | null)
    | ({
        relationTo: 'completions';
        value: string | Completion;
      } | null)
    | ({
        relationTo: 'datasets';
        value: string | Dataset;
      } | null)
    | ({
        relationTo: 'data';
        value: string | Datum;
      } | null)
    | ({
        relationTo: 'evals';
        value: string | Eval;
      } | null)
    | ({
        relationTo: 'evalRuns';
        value: string | EvalRun;
      } | null)
    | ({
        relationTo: 'evalResults';
        value: string | EvalResult;
      } | null)
    | ({
        relationTo: 'functionCalls';
        value: string | FunctionCall;
      } | null)
    | ({
        relationTo: 'modelGroups';
        value: string | ModelGroup;
      } | null)
    | ({
        relationTo: 'models';
        value: string | Model;
      } | null)
    | ({
        relationTo: 'prompts';
        value: string | Prompt;
      } | null)
    | ({
        relationTo: 'providers';
        value: string | Provider;
      } | null)
    | ({
        relationTo: 'schemas';
        value: string | Schema;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'workflows';
        value: string | Workflow;
      } | null)
    | ({
        relationTo: 'workflowCalls';
        value: string | WorkflowCall;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "functions_select".
 */
export interface FunctionsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  deployment?: T;
  active?: T;
  modelGroup?: T;
  output?: T;
  schema?: T;
  code?:
    | T
    | {
        system?: T;
        user?: T;
        types?: T;
        validation?: T;
        deployment?: T;
      };
  workflows?: T;
  functionCalls?: T;
  evals?: T;
  prompts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "completions_select".
 */
export interface CompletionsSelect<T extends boolean = true> {
  tenant?: T;
  function?: T;
  functionName?: T;
  model?: T;
  hash?: T;
  requestId?: T;
  seed?: T;
  output?: T;
  input?: T;
  schema?: T;
  reasoning?: T;
  duration?: T;
  provider?: T;
  refusal?: T;
  error?: T;
  validation?: T;
  debug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  source?: T;
  imported?: T;
  version?: T;
  collection?: T;
  format?: T;
  data?: T;
  evals?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data_select".
 */
export interface DataSelect<T extends boolean = true> {
  dataset?: T;
  content?: T;
  format?: T;
  createdAt?: T;
  updatedAt?: T;
  extractedFrom?: T;
  embeddingType?: T;
  embeddingDim?: T;
  data?: T;
  blob?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  metadata?: T;
  functionCalls?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evals_select".
 */
export interface EvalsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  method?: T;
  metric?: T;
  dataset?: T;
  functions?: T;
  evalRuns?: T;
  resultsTable?: T;
  config?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evalRuns_select".
 */
export interface EvalRunsSelect<T extends boolean = true> {
  eval?: T;
  model?: T;
  function?: T;
  dataset?: T;
  results?: T;
  startTime?: T;
  endTime?: T;
  metrics?: T;
  summary?: T;
  status?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evalResults_select".
 */
export interface EvalResultsSelect<T extends boolean = true> {
  evalRun?: T;
  metrics?: T;
  score?: T;
  pass?: T;
  createdAt?: T;
  result?: T;
  summary?: T;
  details?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "functionCalls_select".
 */
export interface FunctionCallsSelect<T extends boolean = true> {
  function?: T;
  model?: T;
  input?: T;
  output?: T;
  timestamp?: T;
  status?: T;
  error?: T;
  duration?: T;
  cost?: T;
  tokens?: T;
  meta?: T;
  data?: T;
  workflow?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modelGroups_select".
 */
export interface ModelGroupsSelect<T extends boolean = true> {
  name?: T;
  family?: T;
  version?: T;
  active?: T;
  models?: T;
  functions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  description?: T;
  modelGroup?: T;
  provider?: T;
  created?: T;
  contextLength?: T;
  architecture?:
    | T
    | {
        modality?: T;
        tokenizer?: T;
        instructType?: T;
      };
  pricing?:
    | T
    | {
        prompt?: T;
        completion?: T;
        image?: T;
        request?: T;
      };
  capabilities?:
    | T
    | {
        contextLength?: T;
        maxCompletionTokens?: T;
        isModerated?: T;
        multimodal?: T;
        tools?: T;
        vision?: T;
      };
  perRequestLimits?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompts_select".
 */
export interface PromptsSelect<T extends boolean = true> {
  name?: T;
  content?: T;
  description?: T;
  version?: T;
  template?: T;
  category?: T;
  functions?: T;
  variables?:
    | T
    | {
        name?: T;
        description?: T;
        defaultValue?: T;
        required?: T;
        type?: T;
        id?: T;
      };
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  active?: T;
  models?: T;
  endpoint?: T;
  apiUrl?: T;
  apiKey?: T;
  organizationId?: T;
  authType?: T;
  config?: T;
  headers?: T;
  tools?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schemas_select".
 */
export interface SchemasSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  schema?: T;
  schemaYaml?: T;
  type?: T;
  version?: T;
  functions?: T;
  models?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  id?: T;
  domain?: T;
  apiKey?: T;
  active?: T;
  deployed?: T;
  functions?: T;
  users?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  active?: T;
  avatar?: T;
  role?: T;
  permissions?: T;
  preferences?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows_select".
 */
export interface WorkflowsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  deployed?: T;
  active?: T;
  functions?: T;
  workflowRuns?: T;
  config?: T;
  steps?:
    | T
    | {
        name?: T;
        order?: T;
        type?: T;
        function?: T;
        condition?: T;
        loopConfig?: T;
        inputConfig?: T;
        outputConfig?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflowCalls_select".
 */
export interface WorkflowCallsSelect<T extends boolean = true> {
  workflow?: T;
  input?: T;
  output?: T;
  timestamp?: T;
  status?: T;
  error?: T;
  duration?: T;
  success?: T;
  logs?: T;
  metadata?: T;
  functionCalls?: T;
  steps?:
    | T
    | {
        stepId?: T;
        stepName?: T;
        stepOrder?: T;
        status?: T;
        input?: T;
        output?: T;
        error?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdateModels".
 */
export interface TaskUpdateModels {
  input?: unknown;
  output: {
    success?: boolean | null;
    message?: string | null;
    count?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}